import z from "zod";

interface SelectableOption {
  value: string;
  label: string;
}

const phoneRegex = /^\+\d{3}\d{6,9}$/;

const nationalities: SelectableOption[] = [
  { value: "af", label: "Afghan" },
  { value: "al", label: "Albanian" },
  { value: "dz", label: "Algerian" },
  { value: "ad", label: "Andorran" },
  { value: "ao", label: "Angolan" },
  { value: "ag", label: "Antiguan or Barbudan" },
  { value: "ar", label: "Argentine" },
  { value: "am", label: "Armenian" },
  { value: "au", label: "Australian" },
  { value: "at", label: "Austrian" },
  { value: "az", label: "Azerbaijani" },
  { value: "bs", label: "Bahamian" },
  { value: "bh", label: "Bahraini" },
  { value: "bd", label: "Bangladeshi" },
  { value: "bb", label: "Barbadian" },
  { value: "by", label: "Belarusian" },
  { value: "be", label: "Belgian" },
  { value: "bz", label: "Belizean" },
  { value: "bj", label: "Beninese" },
  { value: "bt", label: "Bhutanese" },
  { value: "bo", label: "Bolivian" },
  { value: "ba", label: "Bosnian" },
  { value: "bw", label: "Botswanan" },
  { value: "br", label: "Brazilian" },
  { value: "bn", label: "Bruneian" },
  { value: "bg", label: "Bulgarian" },
  { value: "bf", label: "Burkinese" },
  { value: "mm", label: "Burmese" },
  { value: "bi", label: "Burundian" },
  { value: "kh", label: "Cambodian" },
  { value: "cm", label: "Cameroonian" },
  { value: "ca", label: "Canadian" },
  { value: "cv", label: "Cape Verdean" },
  { value: "td", label: "Chadian" },
  { value: "cl", label: "Chilean" },
  { value: "cn", label: "Chinese" },
  { value: "co", label: "Colombian" },
  { value: "cg", label: "Congolese" },
  { value: "cr", label: "Costa Rican" },
  { value: "hr", label: "Croatian" },
  { value: "cu", label: "Cuban" },
  { value: "cy", label: "Cypriot" },
  { value: "cz", label: "Czech" },
  { value: "dk", label: "Danish" },
  { value: "dj", label: "Djiboutian" },
  { value: "do", label: "Dominican" },
  { value: "ec", label: "Ecuadorean" },
  { value: "eg", label: "Egyptian" },
  { value: "sv", label: "Salvadorean" },
  { value: "gb", label: "English" },
  { value: "er", label: "Eritrean" },
  { value: "ee", label: "Estonian" },
  { value: "et", label: "Ethiopian" },
  { value: "fj", label: "Fijian" },
  { value: "fi", label: "Finnish" },
  { value: "fr", label: "French" },
  { value: "ga", label: "Gabonese" },
  { value: "gm", label: "Gambian" },
  { value: "ge", label: "Georgian" },
  { value: "de", label: "German" },
  { value: "gh", label: "Ghanaian" },
  { value: "gr", label: "Greek" },
  { value: "gd", label: "Grenadian" },
  { value: "gt", label: "Guatemalan" },
  { value: "gn", label: "Guinean" },
  { value: "gy", label: "Guyanese" },
  { value: "ht", label: "Haitian" },
  { value: "hn", label: "Honduran" },
  { value: "hu", label: "Hungarian" },
  { value: "is", label: "Icelander" },
  { value: "in", label: "Indian" },
  { value: "id", label: "Indonesian" },
  { value: "ir", label: "Iranian" },
  { value: "iq", label: "Iraqi" },
  { value: "ie", label: "Irish" },
  { value: "il", label: "Israeli" },
  { value: "it", label: "Italian" },
  { value: "jm", label: "Jamaican" },
  { value: "jp", label: "Japanese" },
  { value: "jo", label: "Jordanian" },
  { value: "kz", label: "Kazakh" },
  { value: "ke", label: "Kenyan" },
  { value: "kw", label: "Kuwaiti" },
  { value: "la", label: "Laotian" },
  { value: "lv", label: "Latvian" },
  { value: "lb", label: "Lebanese" },
  { value: "lr", label: "Liberian" },
  { value: "lt", label: "Lithuanian" },
  { value: "lu", label: "Luxembourger" },
  { value: "mk", label: "Macedonian" },
  { value: "mg", label: "Malagasy" },
  { value: "mw", label: "Malawian" },
  { value: "my", label: "Malaysian" },
  { value: "mv", label: "Maldivian" },
  { value: "ml", label: "Malian" },
  { value: "mt", label: "Maltese" },
  { value: "mr", label: "Mauritanian" },
  { value: "mu", label: "Mauritian" },
  { value: "mx", label: "Mexican" },
  { value: "md", label: "Moldovan" },
  { value: "mc", label: "Monacan" },
  { value: "mn", label: "Mongolian" },
  { value: "me", label: "Montenegrin" },
  { value: "ma", label: "Moroccan" },
  { value: "mz", label: "Mozambican" },
  { value: "na", label: "Namibian" },
  { value: "np", label: "Nepalese" },
  { value: "nl", label: "Dutch" },
  { value: "nz", label: "New Zealander" },
  { value: "ni", label: "Nicaraguan" },
  { value: "ne", label: "Nigerien" },
  { value: "ng", label: "Nigerian" },
  { value: "kp", label: "North Korean" },
  { value: "no", label: "Norwegian" },
  { value: "om", label: "Omani" },
  { value: "pk", label: "Pakistani" },
  { value: "pa", label: "Panamanian" },
  { value: "pg", label: "Papua New Guinean" },
  { value: "py", label: "Paraguayan" },
  { value: "pe", label: "Peruvian" },
  { value: "ph", label: "Filipino" },
  { value: "pl", label: "Polish" },
  { value: "pt", label: "Portuguese" },
  { value: "qa", label: "Qatari" },
  { value: "ro", label: "Romanian" },
  { value: "ru", label: "Russian" },
  { value: "rw", label: "Rwandan" },
  { value: "kn", label: "Saint Kitts and Nevis" },
  { value: "lc", label: "Saint Lucian" },
  { value: "vc", label: "Saint Vincent and the Grenadines" },
  { value: "ws", label: "Samoan" },
  { value: "sm", label: "San Marinese" },
  { value: "st", label: "Sao Tomean" },
  { value: "sa", label: "Saudi" },
  { value: "sn", label: "Senegalese" },
  { value: "rs", label: "Serbian" },
  { value: "sc", label: "Seychellois" },
  { value: "sl", label: "Sierra Leonean" },
  { value: "sg", label: "Singaporean" },
  { value: "sk", label: "Slovak" },
  { value: "si", label: "Slovenian" },
  { value: "so", label: "Somali" },
  { value: "za", label: "South African" },
  { value: "kr", label: "South Korean" },
  { value: "es", label: "Spanish" },
  { value: "lk", label: "Sri Lankan" },
  { value: "sd", label: "Sudanese" },
  { value: "sr", label: "Surinamese" },
  { value: "sz", label: "Swazi" },
  { value: "se", label: "Swedish" },
  { value: "ch", label: "Swiss" },
  { value: "sy", label: "Syrian" },
  { value: "tw", label: "Taiwanese" },
  { value: "tj", label: "Tajik" },
  { value: "tz", label: "Tanzanian" },
  { value: "th", label: "Thai" },
  { value: "tg", label: "Togolese" },
  { value: "to", label: "Tongan" },
  { value: "tt", label: "Trinidadian or Tobagonian" },
  { value: "tn", label: "Tunisian" },
  { value: "tr", label: "Turkish" },
  { value: "tm", label: "Turkmen" },
  { value: "tv", label: "Tuvaluan" },
  { value: "ug", label: "Ugandan" },
  { value: "ua", label: "Ukrainian" },
  { value: "ae", label: "Emirati" },
  { value: "us", label: "American" },
  { value: "uy", label: "Uruguayan" },
  { value: "uz", label: "Uzbekistani" },
  { value: "vu", label: "Vanuatuan" },
  { value: "va", label: "Vatican" },
  { value: "ve", label: "Venezuelan" },
  { value: "vn", label: "Vietnamese" },
  { value: "ye", label: "Yemeni" },
  { value: "zm", label: "Zambian" },
  { value: "zw", label: "Zimbabwean" },
];

const countries: SelectableOption[] = [
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AS", label: "American Samoa" },
  { value: "AD", label: "Andorra" },
  { value: "AO", label: "Angola" },
  { value: "AI", label: "Anguilla" },
  { value: "AQ", label: "Antarctica" },
  { value: "AG", label: "Antigua and Barbuda" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AW", label: "Aruba" },
  { value: "AU", label: "Australia" },
  { value: "AT", label: "Austria" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BS", label: "Bahamas" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BM", label: "Bermuda" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BV", label: "Bouvet Island" },
  { value: "BR", label: "Brazil" },
  { value: "IO", label: "British Indian Ocean Territory" },
  { value: "BN", label: "Brunei Darussalam" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CA", label: "Canada" },
  { value: "CV", label: "Cape Verde" },
  { value: "KY", label: "Cayman Islands" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CX", label: "Christmas Island" },
  { value: "CC", label: "Cocos (Keeling) Islands" },
  { value: "CO", label: "Colombia" },
  { value: "KM", label: "Comoros" },
  { value: "CG", label: "Congo" },
  { value: "CD", label: "Congo, The Democratic Republic of The" },
  { value: "CK", label: "Cook Islands" },
  { value: "CR", label: "Costa Rica" },
  { value: "CI", label: "Cote D'ivoire" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czech Republic" },
  { value: "DK", label: "Denmark" },
  { value: "DJ", label: "Djibouti" },
  { value: "DM", label: "Dominica" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "ET", label: "Ethiopia" },
  { value: "FK", label: "Falkland Islands (Malvinas)" },
  { value: "FO", label: "Faroe Islands" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "FR", label: "France" },
  { value: "GF", label: "French Guiana" },
  { value: "PF", label: "French Polynesia" },
  { value: "TF", label: "French Southern Territories" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" },
  { value: "DE", label: "Germany" },
  { value: "GH", label: "Ghana" },
  { value: "GI", label: "Gibraltar" },
  { value: "GR", label: "Greece" },
  { value: "GL", label: "Greenland" },
  { value: "GD", label: "Grenada" },
  { value: "GP", label: "Guadeloupe" },
  { value: "GU", label: "Guam" },
  { value: "GT", label: "Guatemala" },
  { value: "GG", label: "Guernsey" },
  { value: "GN", label: "Guinea" },
  { value: "GW", label: "Guinea-bissau" },
  { value: "GY", label: "Guyana" },
  { value: "HT", label: "Haiti" },
  { value: "HM", label: "Heard Island and Mcdonald Islands" },
  { value: "VA", label: "Holy See (Vatican City State)" },
  { value: "HN", label: "Honduras" },
  { value: "HK", label: "Hong Kong" },
  { value: "HU", label: "Hungary" },
  { value: "IS", label: "Iceland" },
  { value: "IN", label: "India" },
  { value: "ID", label: "Indonesia" },
  { value: "IR", label: "Iran, Islamic Republic of" },
  { value: "IQ", label: "Iraq" },
  { value: "IE", label: "Ireland" },
  { value: "IM", label: "Isle of Man" },
  { value: "IL", label: "Israel" },
  { value: "IT", label: "Italy" },
  { value: "JM", label: "Jamaica" },
  { value: "JP", label: "Japan" },
  { value: "JE", label: "Jersey" },
  { value: "JO", label: "Jordan" },
  { value: "KZ", label: "Kazakhstan" },
  { value: "KE", label: "Kenya" },
  { value: "KI", label: "Kiribati" },
  { value: "KP", label: "Korea, Democratic People's Republic of" },
  { value: "KR", label: "Korea, Republic of" },
  { value: "KW", label: "Kuwait" },
  { value: "KG", label: "Kyrgyzstan" },
  { value: "LA", label: "Lao People's Democratic Republic" },
  { value: "LV", label: "Latvia" },
  { value: "LB", label: "Lebanon" },
  { value: "LS", label: "Lesotho" },
  { value: "LR", label: "Liberia" },
  { value: "LY", label: "Libyan Arab Jamahiriya" },
  { value: "LI", label: "Liechtenstein" },
  { value: "LT", label: "Lithuania" },
  { value: "LU", label: "Luxembourg" },
  { value: "MO", label: "Macao" },
  { value: "MK", label: "Macedonia, The Former Yugoslav Republic of" },
  { value: "MG", label: "Madagascar" },
  { value: "MW", label: "Malawi" },
  { value: "MY", label: "Malaysia" },
  { value: "MV", label: "Maldives" },
  { value: "ML", label: "Mali" },
  { value: "MT", label: "Malta" },
  { value: "MH", label: "Marshall Islands" },
  { value: "MQ", label: "Martinique" },
  { value: "MR", label: "Mauritania" },
  { value: "MU", label: "Mauritius" },
  { value: "YT", label: "Mayotte" },
  { value: "MX", label: "Mexico" },
  { value: "FM", label: "Micronesia, Federated States of" },
  { value: "MD", label: "Moldova, Republic of" },
  { value: "MC", label: "Monaco" },
  { value: "MN", label: "Mongolia" },
  { value: "ME", label: "Montenegro" },
  { value: "MS", label: "Montserrat" },
  { value: "MA", label: "Morocco" },
  { value: "MZ", label: "Mozambique" },
  { value: "MM", label: "Myanmar" },
  { value: "NA", label: "Namibia" },
  { value: "NR", label: "Nauru" },
  { value: "NP", label: "Nepal" },
  { value: "NL", label: "Netherlands" },
  { value: "AN", label: "Netherlands Antilles" },
  { value: "NC", label: "New Caledonia" },
  { value: "NZ", label: "New Zealand" },
  { value: "NI", label: "Nicaragua" },
  { value: "NE", label: "Niger" },
  { value: "NG", label: "Nigeria" },
  { value: "NU", label: "Niue" },
  { value: "NF", label: "Norfolk Island" },
  { value: "MP", label: "Northern Mariana Islands" },
  { value: "NO", label: "Norway" },
  { value: "OM", label: "Oman" },
  { value: "PK", label: "Pakistan" },
  { value: "PW", label: "Palau" },
  { value: "PS", label: "Palestinian Territory, Occupied" },
  { value: "PA", label: "Panama" },
  { value: "PG", label: "Papua New Guinea" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Peru" },
  { value: "PH", label: "Philippines" },
  { value: "PN", label: "Pitcairn" },
  { value: "PL", label: "Poland" },
  { value: "PT", label: "Portugal" },
  { value: "PR", label: "Puerto Rico" },
  { value: "QA", label: "Qatar" },
  { value: "RE", label: "Reunion" },
  { value: "RO", label: "Romania" },
  { value: "RU", label: "Russian Federation" },
  { value: "RW", label: "Rwanda" },
  { value: "SH", label: "Saint Helena" },
  { value: "KN", label: "Saint Kitts and Nevis" },
  { value: "LC", label: "Saint Lucia" },
  { value: "PM", label: "Saint Pierre and Miquelon" },
  { value: "VC", label: "Saint Vincent and The Grenadines" },
  { value: "WS", label: "Samoa" },
  { value: "SM", label: "San Marino" },
  { value: "ST", label: "Sao Tome and Principe" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "SN", label: "Senegal" },
  { value: "RS", label: "Serbia" },
  { value: "SC", label: "Seychelles" },
  { value: "SL", label: "Sierra Leone" },
  { value: "SG", label: "Singapore" },
  { value: "SK", label: "Slovakia" },
  { value: "SI", label: "Slovenia" },
  { value: "SB", label: "Solomon Islands" },
  { value: "SO", label: "Somalia" },
  { value: "ZA", label: "South Africa" },
  { value: "GS", label: "South Georgia and The South Sandwich Islands" },
  { value: "ES", label: "Spain" },
  { value: "LK", label: "Sri Lanka" },
  { value: "SD", label: "Sudan" },
  { value: "SR", label: "Suriname" },
  { value: "SJ", label: "Svalbard and Jan Mayen" },
  { value: "SZ", label: "Swaziland" },
  { value: "SE", label: "Sweden" },
  { value: "CH", label: "Switzerland" },
  { value: "SY", label: "Syrian Arab Republic" },
  { value: "TW", label: "Taiwan, Province of China" },
  { value: "TJ", label: "Tajikistan" },
  { value: "TZ", label: "Tanzania, United Republic of" },
  { value: "TH", label: "Thailand" },
  { value: "TL", label: "Timor-leste" },
  { value: "TG", label: "Togo" },
  { value: "TK", label: "Tokelau" },
  { value: "TO", label: "Tonga" },
  { value: "TT", label: "Trinidad and Tobago" },
  { value: "TN", label: "Tunisia" },
  { value: "TR", label: "Turkey" },
  { value: "TM", label: "Turkmenistan" },
  { value: "TC", label: "Turks and Caicos Islands" },
  { value: "TV", label: "Tuvalu" },
  { value: "UG", label: "Uganda" },
  { value: "UA", label: "Ukraine" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom" },
  { value: "US", label: "United States" },
  { value: "UM", label: "United States Minor Outlying Islands" },
  { value: "UY", label: "Uruguay" },
  { value: "UZ", label: "Uzbekistan" },
  { value: "VU", label: "Vanuatu" },
  { value: "VE", label: "Venezuela" },
  { value: "VN", label: "Viet Nam" },
  { value: "VG", label: "Virgin Islands, British" },
  { value: "VI", label: "Virgin Islands, U.S." },
  { value: "WF", label: "Wallis and Futuna" },
  { value: "EH", label: "Western Sahara" },
  { value: "YE", label: "Yemen" },
  { value: "ZM", label: "Zambia" },
  { value: "ZW", label: "Zimbabwe" },
];

const genders: SelectableOption[] = [
  { value: "M", label: "Male" },
  { value: "F", label: "Female" },
];

const FormSchema = z.object({
  firstName: z.string().min(1, { message: "First name is required" }),
  middleName: z.string().min(1, { message: "Last name is required" }),
  lastName: z.string().min(1, { message: "Last name is required" }),
  nida: z.string().min(1, { message: "NIDA number is required" }),
  gender: z.string({
    required_error: "Please select your gender.",
  }),
  citizenship: z.string({
    required_error: "Please select your citizenship.",
  }),
  applicantEmail: z
    .string()
    .email({
      message: "Applicant's email must be in a valid format.",
    })
    .optional(),

  applicantPhoneNumber: z
    .string()
    .refine((value) => phoneRegex.test(value), {
      message: "Applicant's phone number must be in a valid format.",
    })
    .optional(),

  streetAddress: z.string({
    required_error: "Street address is required.",
  }),

  city: z.string({
    required_error: "City is required.",
  }),

  region: z.string({
    required_error: "Region is required.",
  }),

  postalCode: z.string({
    required_error: "Postal code is required.",
  }),

  country: z.string({
    required_error: "Country is required.",
  }),

  emergencyContactEmail: z
    .string()
    .email({
      message: "Emergency contact's email must be in a valid format.",
    })
    .optional(),

  emergencyContactPhoneNumber: z
    .string()
    .refine((value) => phoneRegex.test(value), {
      message: "Emergency contact's phone number must be in a valid format.",
    }),

  emergencyContactRelation: z.string({
    required_error: "Relationship to the emergency contact is required.",
  }),
});

export { countries, genders, nationalities, FormSchema };
